language: ruby
rvm:
  - 2.1.2

#script: "LANG=\"en_US.UTF-8\" LC_ALL=\"en_US.UTF-8\" jekyll build"
script: "LANG=\"en_US.UTF-8\" LC_ALL=\"en_US.UTF-8\" script/ci"

git:
  submodules: false

notifications:
  email:
    recipients:
      - leah.bannon@gsa.gov
      - michelle.hertzfeld@gsa.gov
      - gregory.boone@gsa.gov
    on_success: change
    on_failure: change
