sudo: false

language: ruby
rvm:
  - 2.2.3

before_install: npm install

script: "./go ci_build"

git:
  submodules: false

notifications:
  email:
    recipients:
      - gregory.boone@gsa.gov
    on_success: change
    on_failure: change

cache: bundler
