language: ruby
rvm:
  - 2.1.5

script: "./go init && ./go build"
git:
  submodules: false

notifications:
  email:
    recipients:
      - leah.bannon@gsa.gov
      - michelle.hertzfeld@gsa.gov
      - gregory.boone@gsa.gov
    on_success: change
    on_failure: change
