language: ruby
rvm:
  - 2.1.2

install:
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install bourbon

script: "LANG=\"en_US.UTF-8\" LC_ALL=\"en_US.UTF-8\" jekyll build"

notifications:
  email:
    recipients:
      - leah.bannon@gsa.gov
      - michelle.hertzfeld@gsa.gov
      - gregory.boone@gsa.gov
    on_success: change
    on_failure: change

branches:
  only:
    - gh-pages
