markdown: kramdown

title: 18F Digital Services Delivery
description: "18F builds effective, user-centric digital services focused on the interaction between government and the people and businesses it serves."

sass:
  sass_dir: assets/_sass

gems: [bourbon]

destination: _site/dashboard
baseurl: /dashboard
#baseurl: localhost:4000
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- deploy
- go
- gulpfile.js
- node_modules
- package.json
- tests
- vendor

# To disable fetching from the Team API and to build from local data, prefix
# the following field with an underscore.
team_api:
  #baseurl: http://localhost:4001/public/api/
  #suffix: api.json
  baseurl: https://team-api.18f.gov/public/api/
  host: team-api.18f.gov
